class Weathercock::Scorer
  BUCKET_COUNT: Integer
  BUCKET_TTLS: Hash[:hours | :days | :months, Integer]

  def initialize: (klass: Module) -> void

  def hit: (Integer, Symbol, ?increment: Integer) -> Array[untyped]

  def hit_count: (Integer, Symbol, **Integer) -> Integer

  def union: (Symbol, Hash[untyped, untyped], ?decay_factor: Float) -> String

  def top: (Symbol, limit: Integer?, ?decay_factor: Float, **Integer) -> Array[String]

  def hit_counts: (Symbol, ids: Array[untyped], **Integer) -> Hash[String, Integer]

  def rank: (Integer, Symbol, **Integer) -> Integer?

  def remove_hits: (Integer, Symbol) -> Array[untyped]
end
