module Weathercock::Scorable
  def self.included: (Module) -> void
  def self.weathercock_scorer: () -> Weathercock::Scorer

  def id: () -> untyped

  def hit: (Symbol, ?increment: Integer) -> Array[untyped]

  def hit_count: (Symbol, **Integer) -> Integer

  def rank: (Symbol, **Integer) -> Integer?

  def remove_hits: (Symbol) -> Array[untyped]
end

module Weathercock::Scorable::ClassMethods : Module
  def weathercock_scorer: () -> Weathercock::Scorer

  def top: (Symbol, limit: Integer?, ?decay_factor: Float, **untyped) -> Array[String]

  def hit_counts: (Symbol, ids: Array[untyped], **untyped) -> Hash[String, Integer]
end
