module Weathercock
  VERSION: String

  type id = Integer | String

  class Error < StandardError
  end

  class Config
    attr_accessor namespace: String
    attr_accessor redis: untyped

    def initialize: () -> void
  end

  def self.configure: () { (Config) -> void } -> void
  def self.config: () -> Config
end
